exec(open('envelope2.py').read().split('rows,tot=run(62)')[0])
# constants
xLo=[SLO[i]-SHI[i] for i in range(8)]; xHi=[SHI[i]-SLO[i]+dcap[i] for i in range(8)]
def step_consts(xlo,xhi):
    xSlo=[SLO[i]-xhi[i]-dcap[i] for i in range(8)]; xShi=[SHI[i]-xlo[i] for i in range(8)]
    d2lo=sub(xlo,xShi); d2hi=sub(xhi,xSlo); pAlo,pAhi=prod_bounds(alo,ahi,d2lo,d2hi)
    d3lo=sub(xSlo,xHi); d3hi=sub(xShi,xLo); pClo,pChi=prod_bounds(alo,ahi,d3lo,d3hi)
    return add(pClo,neg(pAhi)), add(pChi,neg(pAlo))   # per-step y delta (lo, hi)
dLo0,dHi0=step_consts([0]*8,dcap)     # first step (x canonical)
dLoS,dHiS=step_consts(xLo,xHi)         # steady steps
# y envelope: after first step y in [dLo0, dcap+dHi0]; after n>=1 further steps add (dLoS,dHiS)
def ybound(n):  # n = number of steps completed, n>=1
    return add(dLo0,scale(dLoS,n-1)), add(add(dcap,dHi0),scale(dHiS,n-1))
NMAX=62
yLoMax,yHiMax=ybound(NMAX)   # envelope valid as INPUT to any step d>=1 (after d completed steps, d<=61 <= 62)
def layouts(xlo,xhi,ylo,yhi):
    d1lo=[-xhi[i] for i in range(8)]; d1hi=[dcap[i]-xlo[i] for i in range(8)]
    p1lo,p1hi=prod_bounds(alo,ahi,d1lo,d1hi); r1lo=add(p1lo,ylo); r1hi=add(p1hi,yhi)
    L1=rel_layout(r1lo,r1hi); L1=(L1[0]-(R-1),L1[1],L1[2]-(R-1),L1[3])
    xSlo=[SLO[i]-xhi[i]-dcap[i] for i in range(8)]; xShi=[SHI[i]-xlo[i] for i in range(8)]
    d2lo=sub(xlo,xShi); d2hi=sub(xhi,xSlo); pAlo,pAhi=prod_bounds(alo,ahi,d2lo,d2hi)
    r2lo=sub(add(pAlo,pAlo),scale(yhi,2)); r2hi=sub(add(pAhi,pAhi),scale(ylo,2)); L2=rel_layout(r2lo,r2hi)
    return L1,L2
L1F,L2F=layouts([0]*8,dcap,[0]*8,dcap); L1S,L2S=layouts(xLo,xHi,yLoMax,yHiMax)
res={}
for name,L in (('rel1First',L1F),('rel2First',L2F),('rel1Steady',L1S),('rel2Steady',L2S)):
    k,qb,t,tb=cert_params(*L); res[name]=dict(loMin=L[0],loMax=L[1],hiMin=L[2],hiMax=L[3],kmin=k,qbits=qb,tmin=t,tbits=tb)
    resid=max(abs(L[0]-(R-c)*(k+2**qb-1)-R*(t+2**tb-1)),abs(L[1]-(R-c)*k-R*t),abs(L[2]-(R-1)*(k+2**qb-1)+t),abs(L[3]-(R-1)*k+(t+2**tb-1)))
    print(f"{name:11s} q/t = {qb:3d}/{tb:3d}   resid bits {resid.bit_length()}")
tot=(res['rel1First']['qbits']+res['rel1First']['tbits']+res['rel2First']['qbits']+res['rel2First']['tbits'])+61*(res['rel1Steady']['qbits']+res['rel1Steady']['tbits']+res['rel2Steady']['qbits']+res['rel2Steady']['tbits'])
print(f"cert rows over 62 steps with 4 layouts: {tot} ({tot/62:.1f}/step)  [optimal per-depth was 22097]")
# final canonicalisation layouts (x const-bound, y at n=62) for the ending
RX=rel_layout([xLo[i]-dcap[i] for i in range(8)],xHi); RY=rel_layout([yLoMax[i]-dcap[i] for i in range(8)],yHiMax)
for name,L in (('finalX',RX),('finalY',RY)):
    k,qb,t,tb=cert_params(*L); res[name]=dict(loMin=L[0],loMax=L[1],hiMin=L[2],hiMax=L[3],kmin=k,qbits=qb,tmin=t,tbits=tb); print(f"{name:11s} q/t = {qb}/{tb}")
import json; json.dump(dict(xLo=xLo,xHi=xHi,dLo0=dLo0,dHi0=dHi0,dLoS=dLoS,dHiS=dHiS,NMAX=NMAX,yLoMax=yLoMax,yHiMax=yHiMax,layouts=res),open('var4.json','w'),indent=0)
# Lean fragment
def W(name,v): return f"def {name} : Words ℤ := ![{', '.join(str(x) for x in v)}]"
lean=["-- GENERATED by gen4.py (validated against patchgravity's wideKmin table)",
 W('xLo',xLo),W('xHi',xHi),W('dyLoFirst',dLo0),W('dyHiFirst',dHi0),W('dyLoSteady',dLoS),W('dyHiSteady',dHiS),f"def NMAX : ℕ := {NMAX}"]
for name,d in res.items():
    for f in ('loMin','loMax','hiMin','hiMax','kmin','tmin'): lean.append(f"def {name}_{f} : ℤ := {d[f]}")
    for f in ('qbits','tbits'): lean.append(f"def {name}_{f} : ℕ := {d[f]}")
open('gen4.lean','w').write("\n".join(lean)+"\n"); print("wrote gen4.lean:",len(lean),"defs")
